name: Winston Morrison
favicon: null
layout_spectrum: 1
typography_spectrum: 0.47955
title: 'WINSTON MORRISON - Tap Dancer, Teacher, Performer, Choreographer, Director'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a4b3c1'
    - '#15161d'
    - '#495b78'
    - '#697a8f'
    - '#a8837a'
  brandStrength: 0.590091
  lightness: 0.5
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
